### ISSUE TITLE
CSS file is missing

### ISSUE THREAD

**Issue by timinou** [apvarun/digital-garden-hugo-theme#1]
Hello!

`main.css` is missing. It's in the .gitignore file. Is that voluntary?

Thanks!

**Comment by timinou** [comment]
Ah I see `package.json` has build steps for this. That workflow isn't optimal, though, if we want to get this as a hugo theme (then it's not in the main folder anymore but in `themes/digitalgarden`). What do you recommend?

**Comment by aniqatc** [comment]
I appreciate @timinou opening an issue about this - I knew I couldn't be the only one struggling! The content loads up for me but it's in plain HTML. I've tried everything I could to solve the issue on my own with my very limited coding knowledge (still learning) and of course, Googling & Youtube.. I've even scraped the demo website's code but nothing has been a proper fix.

So I'll keep an eye out on this issue - thank you for starting it @timinou and thanks to @apvarun for creating the theme in the first place (hard to find themes that support a digital garden style).

**Comment by apvarun** [comment]
Hey @timinou and @aniqatc 

Sorry for the communication issue. Here are all the steps to setup the theme, from creating a new hugo site to configuring the theme.

```
hugo new site test-digital-garden
cd test-digital-garden
git clone https://github.com/apvarun/digital-garden-hugo-theme.git themes/digitalgarden
cp themes/digitalgarden/package.json ./package.json
cp themes/digitalgarden/package-lock.json ./package-lock.json
cp themes/digitalgarden/exampleSite/config.toml ./config.toml
cp themes/digitalgarden/tailwind.config.js ./tailwind.config.js
npm install
npm i -g postcss-cli
hugo serve
```
Let me know if this works for you

I will make sure to update the documentation to reflect the same.

**Comment by apvarun** [comment]
Updated the documentation for the theme here:
→ https://digital-garden-hugo-theme.vercel.app/articles/installation/

**Comment by totoroot** [comment]
Thanks for the effort that went into this!

Is there some way to include the CSS as static files in the theme directory so that one doesn't have to mess with the npm ecosystem?

I followed the installation instructions you provided but on `npm install` the first issues came up:
```
npm ERR! code ECONNREFUSED
npm ERR! syscall connect
npm ERR! errno ECONNREFUSED
npm ERR! FetchError: request to https://registry.npmjs.org/yargs-parser/-/yargs-parser-20.2.9.tgz failed, reason: connect ECONNREFUSED 2606:4700::6810:1723:443
...
```

I really like the look of this theme but keeping the npm dependencies for this up-to-date somehow defeats the purpose of using HUGO for a website because of its static nature and ease of use.

**Comment by suicablue** [comment]
Same issue for me. 

When I run "npm run dev" I see this:

[0] > NODE_ENV=development ./node_modules/tailwindcss/lib/cli.js -i ./themes/digitalgarden/assets/css/tailwind.css -o ./static/css/main.css -w

Does it mean a main.css file should appear in "./static/css/"? If it does, then it should be the reason why the css is missing cause I don't see any main.css created in static folder. I wonder why.

**Comment by apvarun** [comment]
@totoroot You are right. It does make sense to include the css file so that it doesn't need to be rebuilt each time even when no style is updated. 
I'll make the change right away.

**Comment by apvarun** [comment]
@suicablue If you pull the latest changes, you can skip rebuilding css locally and focus on content.

**Comment by apvarun** [comment]
Good to hear @totoroot 
Here's my ko.fi 😉   https://ko-fi.com/apvarun
