### ISSUE TITLE
Style in hugo shortcode not rendering

### ISSUE THREAD

**Issue by kaichogami** [apvarun/digital-garden-hugo-theme#18]
Hi. 
I am trying to use [shortcode](https://gohugo.io/content-management/shortcodes/) to insert my custom components. 
It all works fine but style is not getting applied for some reason. The `tailwind` code is not getting rendered. 

`layouts/shortcodes/button.html`
```
<link rel="stylesheet" href="{{ "/css/main.css" | absURL}}" />


<a href="#_" class="relative px-6 py-3 font-bold text-black group">
    <span class="absolute inset-0 w-full h-full transition duration-300 ease-out transform -translate-x-2 -translate-y-2 bg-red-300 group-hover:translate-x-0 group-hover:translate-y-0"></span>
    <span class="absolute inset-0 w-full h-full border-4 border-black"></span>
    <span class="relative">Button Text</span>
    </a>
```

`content/articles/sample.md`

```
---
title: 1. Some topic
date: January 2, 2006
author: Asish Panda
---
{{< button >}}
```

![image](https://user-images.githubusercontent.com/6412770/186706992-ed178ee2-d775-44ea-8588-f4b9617567df.png)

I am not sure why the CSS is not being applied to shortcodes. Any ideas?
Thanks!

**Comment by apvarun** [comment]
Don't see that to be an issue in my end. Followed the steps you mentioned.
![image](https://user-images.githubusercontent.com/8411309/187957576-31b8342d-e935-4d02-bf47-b2b005e68302.png)

The only thing I notice can be an issue is if you added the layouts folder inside of the theme folder. Instead, it should be at the root folder of the site like below:
![image](https://user-images.githubusercontent.com/8411309/187958008-cddcfdbe-ebd7-47f9-9619-834e816c3727.png)


Do you have a repo with issue reproduced?

**Comment by kaichogami** [comment]
Hi,
I got this working by including a minified `tailwind.css` file in static and changing `config` file  to add `custom_css = ["css/tailwind.css", "css/main.css"]`. This solved the problem albiet hackishly. The problem with this approach is the CSS file gets overriden and there are some weird behavrious in colors. 
I think the best solution is to generate a new `main.css` file to include the new css? I am not sure about the exact working which is why I think I am getting stuck here. Would really appreciate pointers here! 

Here is the link to [repo](https://github.com/polycode-in/services_landing_page)

**Comment by apvarun** [comment]
@kaichogami is this still active? I don't see the issue/custom button in the repo shared.

**Comment by kaichogami** [comment]
Hey thanks for replying. I am currently not looking at project i was
working on. So consider it resolved.
Thank you for your help and time. Really appreciate it.
