### ISSUE TITLE
Update social-menu.md to mention Mastodon is also supported

### ISSUE THREAD

**Issue by Skyth3r** [apvarun/digital-garden-hugo-theme#22]
After messing around with the social menu a bit I found that there was already a `mastodonIcon` file within the theme.
It appears to already be supported by the theme but there is no mention of it being supported on the `social-menu.md` article

It might be worth adding this, given Mastodon has recently become a bit more popular

**Comment by Skyth3r** [comment]
Also, where are the social icons sourced from? I was wondering if it would be possible to add more

**Comment by apvarun** [comment]
fyi, there is no one source for icons. Just make sure they are MIT licensed
Usually from https://tabler-icons.io
