### ISSUE TITLE
Update newsletter widget

### ISSUE THREAD

**Issue by Skyth3r** [apvarun/digital-garden-hugo-theme#25]
Revue has announced it will be shutting down at some point in Jan 2023, so it won't be possible to use the existing newsletter widget

Are there any plans to add support for other newsletter platforms such as substack, ghost.org or buttondown?

**Comment by apvarun** [comment]
Good that you brought this up. I think its worthwhile to support other platforms going forward.

**Comment by apvarun** [comment]
Added support for Buttondown and substack

**Comment by Skyth3r** [comment]
Thanks for adding this so quickly!
