### ISSUE TITLE
Articles mobile view cutoff

### ISSUE THREAD

**Issue by Skyth3r** [apvarun/digital-garden-hugo-theme#27]
Just noticed after posting my second article using the theme that the article is cut off and doesn't adjust to the native device screen size

Checked the demo website and also noticed this issue with several articles (1. Theme Installation, 2. Structure and 7. Metatags)

For some reason this seems to only be an issue with some articles and not all of them

Device: iPhone 14 Pro Max 
Browser: Safari

I've also attached some screenshots of the issue from the demo site

![image](https://user-images.githubusercontent.com/14279561/213681368-765211e3-acd4-4643-862f-a7fa1539ddc6.png)

![image](https://user-images.githubusercontent.com/14279561/213680970-7adaeb9a-1b68-4804-8023-04342d1857a7.png)

**Comment by Skyth3r** [comment]
Did a little bit of investigating and found that this issue is resolved once the code blocks with long lines of text are removed from the article

Additionally, when this issue occurs I found the sidebar also decreases in width when viewing an article with this issue but then switches back to the normal width when you view a article without this issue

**Comment by apvarun** [comment]
@Skyth3r I just pushed a fix for the same. Please confirm if things are ok at your end

**Comment by Skyth3r** [comment]
Thanks for the quick fix! Just did a bit of testing, I think the issue with the mobile view cutoff is fixed now but now there's an issue with the sidebar being too wide 😅

This is what the sidebar looks like on my website currently:
<img width="1279" alt="Screenshot 2023-01-21 at 10 11 51 pm" src="https://user-images.githubusercontent.com/14279561/213889036-99d4e631-c820-4766-8dc8-2b242720740e.png">

This is what it looks like in my hugo dev server (localhost):
<img width="1280" alt="Screenshot 2023-01-21 at 10 12 03 pm" src="https://user-images.githubusercontent.com/14279561/213889058-b4eb4ec5-ab20-4b5d-87a7-6fd4ce073fe1.png">

Would you like me to open a new issue for this?
