### ISSUE TITLE
Sincere request

### ISSUE THREAD

**Issue by zlx2019** [apvarun/digital-garden-hugo-theme#45]
Please tell me, will this theme be open source if you use it now? I like it very much

**Comment by apvarun** [comment]
Hey @zlx2019 I don't understand your question here.

This theme has been open source since the start and will remain so (if thats what you mean).

**Comment by zlx2019** [comment]
I mean the website style you are using now https://apvarun.com/

**Comment by zlx2019** [comment]
It seems to be a little different from your open source https://themes.gohugo.io/themes/digital-garden-hugo-theme/

**Comment by apvarun** [comment]
Ah, my website is of a completely separate style. It is in no way related to this theme. Sorry.
At the moment, I don't have any plans of open sourcing it.

**Comment by zlx2019** [comment]
It's ok, thanks for your reply
