### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by TerraPlayz** [apvarun/digital-garden-hugo-theme#8]
Error: add site dependencies: load resources: loading templates: "/home/om/website/MySite/themes/digitalgarden/layouts/_default/_markup/render-link.html:1:1": parse failed: template: _default/_markup/render-link.html:1: unclosed action
om@localhost:~/website/MySite$

**Comment by GeauxWeisbeck4** [comment]
Hi can you share your files so I can see what could have been missing on that .html file or in the dependencies? I think I know the issue.

**Comment by omxpro** [comment]
Hey there! I've fixed the issue by using the ExampleSite folder and moving it to my git repo and then pushing it and editing it

**Comment by omxpro** [comment]
Is there a way to change the color theme from blue to orange or "fire"

**Comment by GeauxWeisbeck4** [comment]
> Is there a way to change the color theme from blue to orange or "fire"

Yes. Edit /assets/css/tailwind.css 

[Here's the TailwindCSS site](tailwindcss.com)

**Comment by omxpro** [comment]
> > Is there a way to change the color theme from blue to orange or "fire"
> 
> Yes. Edit /assets/css/tailwind.css
> 
> [Here's the TailwindCSS site](tailwindcss.com)

And how to set default theme to dark?

**Comment by omxpro** [comment]
@GeauxWeisbeck4?

**Comment by developfast** [comment]
> Hey there! I've fixed the issue by using the ExampleSite folder and moving it to my git repo and then pushing it and editing it

I am running into the same problem as well, could you please clarify how you fixed it?

**Comment by omxpro** [comment]
> > Hey there! I've fixed the issue by using the ExampleSite folder and moving it to my git repo and then pushing it and editing it
> 
> I am running into the same problem as well, could you please clarify how you fixed it?

What I did was, i firstly cloned this repo. After that I copied my contents. And pasted in the example site. Delete everything that was out of exampleSite. And done

**Comment by developfast** [comment]
> > > Hey there! I've fixed the issue by using the ExampleSite folder and moving it to my git repo and then pushing it and editing it
> > 
> > 
> > I am running into the same problem as well, could you please clarify how you fixed it?
> 
> What I did was, i firstly cloned this repo. After that I copied my contents. And pasted in the example site. Delete everything that was out of exampleSite. And done

This includes the package.json and package-lock.json files. So we are left with a directory structure that looks like this:
example-Site
 -content
 -data
 -config.toml

Is this right?

**Comment by developfast** [comment]
I am still getting the same error. Could you share a link to your repo which worked? Or a complete directory structure.

**Comment by omxpro** [comment]
> I am still getting the same error. Could you share a link to your repo which worked? Or a complete directory structure.

Yea Lemme find it

**Comment by omxpro** [comment]
https://github.com/omxpro/web

**Comment by omxpro** [comment]
The public folder outputs to https://GitHub.com/omxpro/omxpro.github.io

**Comment by developfast** [comment]
Thanks @omxpro, will have a look.

**Comment by GeauxWeisbeck4** [comment]
> > > Is there a way to change the color theme from blue to orange or "fire"
> 
> > 
> 
> > Yes. Edit /assets/css/tailwind.css
> 
> > 
> 
> > [Here's the TailwindCSS site](tailwindcss.com)
> 
> 
> 
> Also what do I edit in this?

You could edit the className in the body class in the tailwind.css file or set the theme in your tailwind.config.js file. 

For future reference, please read TailwindCSS to understand how it works or email me like I mentioned earlier and I'd be happy to teach you.
